### ISSUE TITLE
Movie bug while interactive testing

### ISSUE THREAD

**Issue by boslbi92** [emora-chat/emora#70]
--- Logging error ---
Traceback (most recent call last):
  File "/home/jason/Documents/EmoraCobot/cobot/miniskills/emora_modules/emora_ranking_strategy.py", line 60, in rank
    topic_response, topic_score = options[topic_module]
KeyError: 'movies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/anaconda3/envs/emora/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/jason/anaconda3/envs/emora/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/jason/anaconda3/envs/emora/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/jason/anaconda3/envs/emora/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/jason/Documents/EmoraCobot/cobot/bin/interactive_mode.py", line 368, in <module>
    ask.process(utterance)
  File "/home/jason/Documents/EmoraCobot/cobot/bin/interactive_mode.py", line 241, in process
    response_text = self.process_successful_ask_intent_request(output)
  File "/home/jason/Documents/EmoraCobot/cobot/bin/interactive_mode.py", line 258, in process_successful_ask_intent_request
    response_text = self.process_event(event)
  File "/home/jason/Documents/EmoraCobot/cobot/bin/interactive_mode.py", line 273, in process_event
    result = lambda_handler_method(event=event, context={})
  File "/home/jason/Documents/EmoraCobot/cobot/emorav2/emora.py", line 311, in lambda_handler
    alexa_response = abtest.run(GLOBAL_USER_TABLE_NAME)
  File "/home/jason/Documents/EmoraCobot/cobot/cobot_core/abtest.py", line 174, in run
    return selected_socialbot.execute()
  File "/home/jason/Documents/EmoraCobot/cobot/cobot_core/cobot_handler.py", line 209, in execute
    response_generator_output, should_end_session = dm.select_response(features)
  File "/home/jason/Documents/EmoraCobot/cobot/miniskills/emora_modules/emora_dialog_manager.py", line 101, in select_response
    response += self.rank_wrapper(responses_list, filtered_output_responses, filtered_module_list, output_responses_dict)
  File "/home/jason/Documents/EmoraCobot/cobot/miniskills/emora_modules/emora_dialog_manager.py", line 133, in rank_wrapper
    response = self.ranking_strategy.rank(output_responses_dict, filtered_module_list)
  File "/home/jason/Documents/EmoraCobot/cobot/miniskills/emora_modules/emora_ranking_strategy.py", line 65, in rank
    self.logger.info("Utilizing topic classifier in ranking decision failed, so using original choice - error: ", e)
Message: '319696976167876858547719849954737620035 amzn1.echo-api.session.localinteraction-i33xtr2flmqhimw8 Utilizing topic classifier in ranking decision failed, so using original choice - error: '
Arguments: (KeyError('movies'),)

**Comment by sergey-volokhin** [comment]
I could not reproduce it.
It is probably the latency issue when running locally.
